#ifndef STRAPPY_PALETTE_H
#define STRAPPY_PALETTE_H

#define STRAPPY_PRIMARY_TINT_RED 142.0f
#define STRAPPY_PRIMARY_TINT_GREEN 27.0f
#define STRAPPY_PRIMARY_TINT_BLUE 207.0f

#define STRAPPY_DARK_TINT_RED 114.0f
#define STRAPPY_DARK_TINT_GREEN 22.0f
#define STRAPPY_DARK_TINT_BLUE 166.0f

#define STRAPPY_MUTED_PURPLE_RED 137.0f
#define STRAPPY_MUTED_PURPLE_GREEN 102.0f
#define STRAPPY_MUTED_PURPLE_BLUE 154.0f

#define STRAPPY_LIGHT_PURPLE_RED 216.0f
#define STRAPPY_LIGHT_PURPLE_GREEN 194.0f
#define STRAPPY_LIGHT_PURPLE_BLUE 229.0f

#endif
