#ifndef STRAPPY_PALETTE_H
#define STRAPPY_PALETTE_H

#define STRAPPY_PRIMARY_TINT_RED 142.0f
#define STRAPPY_PRIMARY_TINT_GREEN 27.0f
#define STRAPPY_PRIMARY_TINT_BLUE 207.0f
#define STRAPPY_PRIMARY_TINT_HEX "#8e1bcf"

#define STRAPPY_DARK_TINT_RED 114.0f
#define STRAPPY_DARK_TINT_GREEN 22.0f
#define STRAPPY_DARK_TINT_BLUE 166.0f
#define STRAPPY_DARK_TINT_HEX "#7216a6"

#define STRAPPY_MUTED_PURPLE_RED 137.0f
#define STRAPPY_MUTED_PURPLE_GREEN 102.0f
#define STRAPPY_MUTED_PURPLE_BLUE 154.0f
#define STRAPPY_MUTED_PURPLE_HEX "#89669a"

#define STRAPPY_LIGHT_PURPLE_RED 216.0f
#define STRAPPY_LIGHT_PURPLE_GREEN 194.0f
#define STRAPPY_LIGHT_PURPLE_BLUE 229.0f
#define STRAPPY_LIGHT_PURPLE_HEX "#d8c2e5"

#define STRAPPY_SECTION_HEADER_TINT_RED 149.4166667f
#define STRAPPY_SECTION_HEADER_TINT_GREEN 138.8583333f
#define STRAPPY_SECTION_HEADER_TINT_BLUE 153.9416667f
#define STRAPPY_SECTION_HEADER_TINT_HEX "#958b9a"

/* Semantic application colors shared by the C-rendered conversation and the
 * browser application shell. Keep these compatible with legacy WebKit, which
 * is why the renderer uses concrete colors rather than CSS custom properties. */
#define STRAPPY_PALETTE_PAGE_BACKGROUND "#fbfafc"
#define STRAPPY_PALETTE_PRIMARY_TEXT "#302e31"
#define STRAPPY_PALETTE_PANEL_BACKGROUND "#f0edf2"
#define STRAPPY_PALETTE_SECONDARY_TEXT "#676268"
#define STRAPPY_PALETTE_CONTROL_TEXT "#5d5262"
#define STRAPPY_PALETTE_SECTION_BACKGROUND "#d7d1d9"
#define STRAPPY_PALETTE_SURFACE_BACKGROUND "#fff"
#define STRAPPY_PALETTE_BORDER "#a49da6"
#define STRAPPY_PALETTE_STRONG_SURFACE "#b9b2bc"
#define STRAPPY_PALETTE_STRONG_BORDER "#716a73"
#define STRAPPY_PALETTE_ERROR "#9a3e47"
#define STRAPPY_PALETTE_ERROR_BACKGROUND "#e7c8cc"
#define STRAPPY_PALETTE_WARNING "#755a00"
#define STRAPPY_PALETTE_TERMINAL_BORDER "#837b86"
#define STRAPPY_PALETTE_TERMINAL_BACKGROUND "#f7f5f8"
#define STRAPPY_PALETTE_TERMINAL_TEXT "#2a282b"
#define STRAPPY_PALETTE_TERMINAL_HEADER "#ddd8e0"

#endif
